### ISSUE TITLE
Hide orphan nodes

### ISSUE THREAD

**Issue by epinapala** [nylen/d3-process-map#13]
Is there a way to hide the nodes which don't have at least one child or isn't a parent to at least one child?

Please help, thanks!

**Comment by nylen** [comment]
@epinapala I'd start with something like this, inserted at [`script.js#L54`](https://github.com/nylen/d3-process-map/blob/9cc4ab7abfb0a3a9c921d51570903fc2640044df/script.js#L54):

```js
for (var name in graph.data) {
    var obj = graph.data[name];
    if (!obj.depends.length && !obj.dependedOnBy.length) {
        delete graph.data[name];
    }
}
```

Beware of bugs in the above code; I have only proved it correct, not tried it. [\[#\]](https://www.brainyquote.com/quotes/quotes/d/donaldknut181622.html)

Closing since to me this is a pretty uncommon use-case.
